### ISSUE TITLE
local installation

### ISSUE THREAD

**Issue by josefkr** [rug-compling/conllu-viewer#2]
Hi, I use your viewer a lot and would like to be able to change the annotations shown in the boxes for the tokens and/or on the tooltips. In particular, I would like to display some info from the MISC column 

For that reason, I cloned your repo and  modified  the code. But somehow, on my local machine, after I  submit a file, I only see the contents of the "form" file.  (I put the conllu-viewer dir under /var/www/html and gave ownership of the dir to www-data)

Would you have a pointer for me on how to use the viewer locally?

**Comment by pebbe** [comment]
You need to set up your web server to support cgi scripts. Consult the documentation of whatever web server you are using.
